### ISSUE TITLE
富文本问题

### ISSUE THREAD

**Issue by DaiYiWen** [iOS-Strikers/OCBarrage#5]
使用富文本添加文字带表情的,只显示文字不显示表情,如果纯表情就会显示.

**Comment by w1531724247** [comment]
> 使用富文本添加文字带表情的,只显示文字不显示表情,如果纯表情就会显示.

贴一下你添加"文字带表情"的代码

**Comment by DaiYiWen** [comment]
<img width="888" alt="20181130133343" src="https://user-images.githubusercontent.com/24957235/49270516-bb5c4380-f4a4-11e8-8a4e-843f045469d8.png">
<img width="1008" alt="20181130133430" src="https://user-images.githubusercontent.com/24957235/49270517-bb5c4380-f4a4-11e8-9580-b861ee45b055.png">

**Comment by w1531724247** [comment]
> 使用富文本添加文字带表情的,只显示文字不显示表情,如果纯表情就会显示.

![87d5e67d-2da6-470b-8b9e-ebf003c52597](https://user-images.githubusercontent.com/16831997/49270935-8224d300-f4a6-11e8-8419-4d1e73bb05c3.png)

**Comment by DaiYiWen** [comment]
好的,谢谢
