### ISSUE TITLE
控制台一直输出这个有办法优化吗？

### ISSUE THREAD

**Issue by onehao16** [iOS-Strikers/OCBarrage#8]
CGContextAddArc: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by w1531724247** [comment]
> CGContextAddArc: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

这主要是demo里addBarrage这个方法里调用的是延时执行造成的， 把延时执行改成直接调用就不会有这样的提示了
